# Generated by Django 4.1.2 on 2022-11-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
                ('currancy', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
