# Generated by Django 4.1.2 on 2022-11-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countriescard',
            name='iso_4217_code',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
