# Generated by Django 4.1.2 on 2022-11-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_countriescard_iso_4217_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='countriescard',
            name='calling_code',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countriescard',
            name='driving_side',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countriescard',
            name='internet_tld',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
