# Generated by Django 4.1.3 on 2022-12-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_alter_countriescard_calling_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countriescard',
            name='calling_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='countriescard',
            name='country_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='countriescard',
            name='currancy',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='countriescard',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='countriescard',
            name='driving_side',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='countriescard',
            name='internet_tld',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='countriescard',
            name='iso_4217_code',
            field=models.CharField(max_length=3),
        ),
    ]
