# Generated by Django 4.1.3 on 2022-12-06 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countries', '0007_usercountriesrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='countriescard',
            name='reader',
            field=models.ManyToManyField(related_name='reader_countries', through='countries.UserCountriesRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='countriescard',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_countries', to=settings.AUTH_USER_MODEL),
        ),
    ]
