# Generated by Django 4.1.3 on 2022-12-06 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countries', '0008_countriescard_reader_alter_countriescard_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countriescard',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_country', to=settings.AUTH_USER_MODEL),
        ),
    ]
